# Generated by Django 5.0.6 on 2024-05-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название работы')),
                ('anons', models.CharField(max_length=50, verbose_name='Анонсыы')),
                ('full_text', models.TextField(verbose_name='Описание работы')),
                ('date', models.DateField(verbose_name='Дата загрузки')),
            ],
        ),
    ]
